### ISSUE TITLE
Compile does not show success message when updating YSI-Includes-nightly

### ISSUE THREAD

**Issue by thangtcm** [Zeex/qawno#3]
![image](https://github.com/Zeex/qawno/assets/23113822/0deb0e38-9c12-43c1-b071-3e006cf1b473)
It's really quite annoying when a new version comes out, but there are no specific instructions on integration with the current gamemode. When I tried to update using qawno, it almost always failed to update YSI, and the compiler showed nothing.

**Comment by Zeex** [comment]
I think you want to file an issue to OMP's repo instead: https://github.com/openmultiplayer/qawno.git

In my version there is no functionality to update libraries.

**Comment by Zeex** [comment]
Also, have you checked if pawncc.exe is running in the task manager? It could be the case that your script is still compiling. 

Or you can try compiling directly from the command line to eliminate qawno from the equation (via the pawncc command shown at the bottom).
